@baseURI = http://localhost:3000

GET  {{baseURI}}/bayes/ HTTP/1.1
Content-Type: application/json

{
    "lung_cancer_probability": 0.40,
    "tuberculosis_probability": 0.35,
    "pneumonia_probability": 0.25,
    "evidence": ["coughing_blood", "fatigue", "weight_loss"]
}